
export const SHOW_MENU = "SHOW_MENU"
export const HIDE_MENU = "HIDE_MENU"
export const NEXT_SLIDE = "NEXT_SLIDE"
export const PREV_SLIDE = "PREV_SLIDE"
export const SET_SLIDE = "SET_SLIDE"
export const SET_USERS = "SET_USERS"
export const GET_USERS = "GET_USERS"
export const VALID = "VALID"
export const INVALID = "INVALID"
export const LOGIN = "LOGIN"
export const LOGOUT = "LOGOUT"
export const NUMBER_OF_SLIDE = "NUMBER_OF_SLIDE"
export const ADD_TICKET = "ADD_TICKET"
export const REMOVE_TICKET = "REMOVE_TICKET"
export const ADD_USER = "ADD_USER"
export const REMOVE_USER = "REMOVE_USER"
export const SET_EVENTS = "SET_EVENTS"
export const LOADING_EVENTS = "LOADING_EVENTS"
export const LOADING_EVENTS_DONE = "LOADING_EVENTS_DONE"
export const IS_ERROR_TRUE = "IS_ERROR_TRUE"
export const IS_ERROR_FALSE = "IS_ERROR_FALSE"

